spring:
  application:
    name: community-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      "[hibernate.type.preferred_enum_jdbc_type]": VARCHAR
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1

server:
  port: ${COMMUNITY_HTTP_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

app:
  environment: ${APP_ENV}
  internal-grpc-token: ${INTERNAL_GRPC_TOKEN}
  opensearch:
    host: ${OPENSEARCH_HOST}
    port: ${OPENSEARCH_PORT}
    scheme: ${OPENSEARCH_SCHEME:http}
    username: ${OPENSEARCH_USERNAME:}
    password: ${OPENSEARCH_PASSWORD:}

grpc:
  server:
    port: ${COMMUNITY_GRPC_PORT}
    security:
      enabled: ${GRPC_SERVER_SECURITY_ENABLED}
      client-auth: ${GRPC_SERVER_SECURITY_CLIENT_AUTH}
  client:
    GLOBAL:
      negotiationType: ${GRPC_CLIENT_NEGOTIATION_TYPE}
    user-service:
      address: ${USER_SERVICE_GRPC}
